### ISSUE TITLE
Basic Kubernetes installation failing on yum steps

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#79]
## What you expected to happen?

Kubernetes to install on my node

## What happened?

I get this error:

```
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: /Stage[main]/Kubernetes::Packages/Package[docker-engine]/ensure: change from 'purged' to '1.12.6' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubernetes-cni-0.5.1' returned 1: One of the configured repositories failed (docker),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
. . . 
```

## How to reproduce it?

Puppetfile contents:
```
# These are dependencies for Puppet
mod 'puppetlabs-stdlib', '4.24.0'
mod 'puppetlabs-apt', '4.5.1'
mod 'puppetlabs-translate', '1.0.0'

# Some nodes run docker but not kubernetes
mod 'puppetlabs-docker', '1.1.0'

# These are dependencies for kubernetes
mod 'puppet-archive', '2.0.0'
mod 'maestrodev-wget', '1.7.0'

mod 'puppetlabs-kubernetes', '1.0.3'
```

Here's the simple code I used:
```
  class { 'kubernetes':
    controller => true,
    bootstrap_controller => true,
  }
```

## Versions:

```
$ puppet --version
5.3.5

$ kubectl version
(not installed yet)

$ docker version OR crictl version
(not installed yet)

$ facter os
{
  architecture => "x86_64",
  distro => {
    codename => "Maipo",
    description => "Red Hat Enterprise Linux Workstation release 7.4 (Maipo)",
    id => "RedHatEnterpriseWorkstation",
    release => {
      full => "7.4",
      major => "7",
      minor => "4"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.4",
    major => "7",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}

$ puppet module list
/etc/puppetlabs/code/environments/production/modules (no modules installed)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)
```

**Comment by scotty-c** [comment]
@vrmerlin this has been fixed in master and will make the next release. If you want to use the module you have and not master change the the cni version to ` $cni_version = '0.6.0'` or in hiera `kubernetes::cni_version: 0.6.0`

**Comment by vrmerlin** [comment]
I switched to the master branch, so my Puppetfile now contains this:

```
mod 'puppetlabs-kubernetes',
   :git => 'https://github.com/puppetlabs/puppetlabs-kubernetes.git'
```

I removed all my modules, and re-grabbed them with r10k, to make sure I was using the master branch.

However, I still get the same errors:

```
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: /Stage[main]/Kubernetes::Packages/Package[docker-engine]/ensure: change from 'purged' to '1.12.6' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubernetes-cni-0.6.0' returned 1: Error downloading packages:
  kubelet-1.9.1-0.x86_64: [Errno 256] No more mirrors to try.

Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: /Stage[main]/Kubernetes::Packages/Package[kubernetes-cni]/ensure: change from 'purged' to '0.6.0' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubernetes-cni-0.6.0' returned 1: Error downloading packages:
  kubelet-1.9.1-0.x86_64: [Errno 256] No more mirrors to try.

Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubelet-1.9.2' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: /Stage[main]/Kubernetes::Packages/Package[kubelet]/ensure: change from 'purged' to '1.9.2' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubelet-1.9.2' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubectl-1.9.2' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: /Stage[main]/Kubernetes::Packages/Package[kubectl]/ensure: change from 'purged' to '1.9.2' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install kubectl-1.9.2' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
```

**Comment by scotty-c** [comment]
@vrmerlin There was a design choice not to add the Docker module as a dependency to this module as all you need from Docker is the package. As the work on cri-containerd moves along I think you will see that become the default runtime for the cluster. So we have added that already. So we won't be adding the Docker module to this module.

**Comment by scotty-c** [comment]
@vernelindner can you please try master now without applying the Docker module. We added some small changes yesterday to make the module work more efficiently on RHEL

**Comment by AranVinkItility** [comment]
I can see the 1.0.3 version failing on the incorrect yum repo being added; https://yum.dockerproject.org/repo/main/redhat/7 which does not exist anymore.
Switching to master branch of this repo fixed it for me.

When can we expect a new release, since 1.0.3 is broken for RedHat/CentOS at this moment?

**Comment by scotty-c** [comment]
@AranVinkItility that will be coming in the next day or so

**Comment by scotty-c** [comment]
closing due to the fix being released in v1.1.0

**Comment by vrmerlin** [comment]
This still isn't working for me; i just tried it again, with 1.1.0.  I'm getting the error:

```
Error: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
Error: /Stage[main]/Kubernetes::Packages/Package[docker-engine]/ensure: change from 'purged' to '1.12.6' failed: Could not update: Execution of '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6' returned 1: Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
```
The ```/etc/yum.repos.d/docker.repo``` contains this:

```
[docker]
name=docker
baseurl=https://yum.dockerproject.org/repo/main/centos/7
gpgcheck=True
gpgkey=https://yum.dockerproject.org/gpg
```

This looks suspicious, because I am on RedHat 7, not Centos. The files in that baseurl location all have 'centos' in it. I understand that centos RPMs can run on Redhat, but just running the yum command standalone doesn't install the package:

```
# /bin/yum -d 0 -e 0 -y install docker-engine-1.12.6
Error: Nothing to do
Loaded plugins: langpacks, product-id, subscription-manager, versionlock
```

Any ideas? I'm dead in the water.

John

**Comment by AranVinkItility** [comment]
The CentOS packages are the correct ones, since Docker does not release RedHat packages through Yum (just check the yum repo root at https://yum.dockerproject.org/repo/main/)

As to why it has nothing to do: what happens when you run `docker --version`?

**Comment by ndelic0** [comment]
Have the same problem here.
Module will install only docker-engine package from official docker repo. That one will get in conflict with docker packages install from centos extras.

Solved this with uninstalling centos packages.

**Comment by vrmerlin** [comment]
@AranVinkItility  I can't give the docker version number -- that's the problem! The docker package that the Kubernetes module is attempting to install, given the repo setup it does and the docker package name, doesn't work.

**Comment by AranVinkItility** [comment]
@vrmerlin I see you are using an older version of the Kubernetes module (1.0.3)
Can you try changing it to 1.1.0? I'm running 1.1.0 myself on RHEL 7.4 and did not run into this issue.

So try changing `mod 'puppetlabs-kubernetes', '1.0.3'` to `mod 'puppetlabs-kubernetes', '1.1.0'` in your Puppetfile

**Comment by AranVinkItility** [comment]
@vrmerlin I just checked my yum repo config and it's the same as yours.
If I run `yum repo list docker*` it gives me the following output:
```
Installed Packages
docker-engine.x86_64 1.12.6-1.el7.centos @docker
docker-engine-selinux.noarch 17.05.0.ce-1.el7.centos @docker
Available Packages
...
```

Running the 1.1.0 module on a clean RHEL 7.4 machine gives me the following output:
```
Debug: Prefetching inifile resources for yumrepo
Debug: Executing: '/bin/rpm -q docker-engine --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Debug: Executing: '/bin/yum -d 0 -e 0 -y list docker-engine'
Debug: Package[docker-engine](provider=yum): Ensuring => 1.12.6
Debug: Package[docker-engine](provider=yum): Detected Arch argument in package! - Moving arch to end of version string
Debug: Executing: '/bin/rpm -q docker-engine --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Debug: Executing: '/bin/yum -d 0 -e 0 -y install docker-engine-1.12.6'
Debug: Executing: '/bin/rpm -q docker-engine --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Notice: /Stage[main]/Kubernetes::Packages/Package[docker-engine]/ensure: created
Debug: /Stage[main]/Kubernetes::Packages/Package[docker-engine]: The container Class[Kubernetes::Packages] will propagate my refresh event
```
Is this the same output as you are getting? (minus the errors of course)
